server:
  port: 8890

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/small?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123123
  redis:
    database: 0
    host: 172.28.50.78
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 120s
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "hello:world:"
    expire:
      authCode: 120 # 验证码超期时间